name: Build and Archive iOS Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build Archive
        run: |
          xcodebuild -project WWWeeb.xcodeproj -scheme WWWeeb -sdk iphoneos -configuration Release archive -archivePath $PWD/build/WWWeeb.xcarchive CODE_SIGNING_ALLOWED=NO

      - name: Create IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/WWWeeb.xcarchive -exportPath $PWD/build -exportOptionsPlist exportOptions.plist CODE_SIGNING_ALLOWED=NO
          cd build
          zip -r WWWeeb.ipa Payload
          mv build/WWWeeb.ipa.zip build/WWWeeb.ipa

      - name: Upload IPA to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/YOUR_SCHEME.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
