name: Build and Archive iOS Project

on:
  push:
    tags:
      - "*.*.*.*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      - name: Build Archive
        run: |
          xcodebuild -project StoryHub.xcodeproj -scheme StoryHub -sdk iphoneos -configuration Release archive -archivePath $PWD/build/StoryHub.xcarchive CODE_SIGNING_ALLOWED=NO
      - name: Create IPA
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          mkdir Payload
          mv ./build/StoryHub.xcarchive/Products/Applications/StoryHub.app ./Payload
          zip -r StoryHub-v${TAG_NAME}.ipa Payload
          echo "IPA_NAME=StoryHub-v${TAG_NAME}.ipa" >> $GITHUB_ENV
      - name: Upload IPA to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.IPA_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
